name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # https://crontab.guru/every-hour
    - cron: 0 0 * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1
        with:
          merge_method: squash
          # Source: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
          time_zone: "Australia/Melbourne"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}